version: "3.8"
services:
  db:
    image: postgres
    container_name: wisheo-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: wisheo_db
    ports:
      - "5433:5432"
